server:
  port: 8088
  servlet:
    context-path: /bp-mall

spring:
  application:
    name: bp-mall
  cloud:
    nacos:
      discovery:
        server-addr: 120.78.137.159:8848
    sentinel:
      transport:
        # sentinel控制台的地址
        dashboard: 120.78.137.159:8080
      # 立即加载
      eager: true

feign:
  sentinel:
    # 默认是没有提示的
    enabled: true