server:
  port: 8090
  servlet:
    context-path: /bp-business

spring:
  application:
    name: bp-business
  cloud:
    nacos:
      discovery:
        server-addr: 120.78.137.159:8848
    sentinel:
      transport:
        # sentinel控制台的地址
        dashboard: 120.78.137.159:8080
      # 立即加载
      eager: true